services:
  - type: web
    name: yahya-majrashi-portfolio
    runtime: static
    plan: free
    buildCommand: ""
    staticPublishPath: ./
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
